### ISSUE TITLE
Maximum size of messages

### ISSUE THREAD

**Issue by grundid** [Losant/losant-mqtt-arduino#11]
I'm having issues with larger messages. Messages with more than 76 characters are not send.
After looking at the source code I've noticed that you have a StaticJsonBuffer with 100 bytes in the sendState method.

Since the examples already use StaticJsonBuffer with 500 bytes I guess it would be good to increase the buffer or maybe document the limitation.

**Comment by anaptfox** [comment]
@grundid, thanks for bringing this up. I can add a note about it in the README.md

Overall, the issue has to do with the underlying MQTT client ([PubSubClient](https://github.com/knolleary/pubsubclient)) we use. 

For more info: 
https://forums.losant.com/t/sending-commands-with-larger-payloads/135
https://github.com/knolleary/pubsubclient/issues/110
