### ISSUE TITLE
Issue with JSON library migration from 5 to 6

### ISSUE THREAD

**Issue by mwwojcik2017** [Losant/losant-mqtt-arduino#13]
Hi there, please read an article: https://arduinojson.org/v6/doc/upgrade/
It looks like you will need to rewrite your library as there is legacy code inside.
See following error messages I got:
"Arduino: 1.8.9 (Windows Store 1.8.21.0) (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Disabled, All SSL ciphers (most compatible), 4M (no SPIFFS), v2 Higher Bandwidth, Disabled, None, Only Sketch, 115200"

C:\xxx\Arduino\libraries\losant-mqtt-arduino-master\src\internal\LosantDevice.cpp:8:11: error: DynamicJsonBuffer is a class from ArduinoJson 5. Please see arduinojson.org/upgrade to learn how to upgrade your program to ArduinoJson version 6

   DynamicJsonBuffer jsonBuffer;

           ^

C:\xxx\Arduino\libraries\losant-mqtt-arduino-master\src\internal\LosantDevice.cpp:90:11: error: StaticJsonBuffer is a class from ArduinoJson 5. Please see arduinojson.org/upgrade to learn how to upgrade your program to ArduinoJson version 6

   StaticJsonBuffer<100> jsonBuffer;

           ^

C:\xxx\Arduino\libraries\losant-mqtt-arduino-master\src\internal\LosantDevice.cpp: In function 'void commandReceived(char*, byte*, unsigned int)':

C:\xxx\Arduino\libraries\losant-mqtt-arduino-master\src\internal\LosantDevice.cpp:8:21: error: 'jsonBuffer' was not declared in this scope

   DynamicJsonBuffer jsonBuffer;

                     ^

C:\xxx\Arduino\libraries\losant-mqtt-arduino-master\src\internal\LosantDevice.cpp:11:11: error: 'ArduinoJson::JsonObject' has no member named 'success'

   if(root.success()) {

           ^

C:\xxx\Arduino\libraries\losant-mqtt-arduino-master\src\internal\LosantDevice.cpp:14:41: error: 'ArduinoJson6120_000001::enable_if<true, ArduinoJson6120_000001::MemberProxy<const ArduinoJson6120_000001::ObjectRef&, const char*> >::type' has no member named 'asObject'

     command.payload = &(root["payload"].asObject());

                                         ^

C:\xxx\Arduino\libraries\losant-mqtt-arduino-master\src\internal\LosantDevice.cpp: In member function 'void LosantDevice::sendState(ArduinoJson::JsonObject&)':

C:\xxx\Arduino\libraries\losant-mqtt-arduino-master\src\internal\LosantDevice.cpp:90:19: error: expected primary-expression before '<' token

   StaticJsonBuffer<100> jsonBuffer;

                   ^

C:\xxx\Arduino\libraries\losant-mqtt-arduino-master\src\internal\LosantDevice.cpp:90:25: error: 'jsonBuffer' was not declared in this scope

   StaticJsonBuffer<100> jsonBuffer;

                         ^

C:\xxx\Arduino\libraries\losant-mqtt-arduino-master\src\internal\LosantDevice.cpp:96:8: error: 'ArduinoJson::JsonObject' has no member named 'printTo'

   root.printTo(stateStr);

        ^

exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
"

**Comment by mwwojcik2017** [comment]
I am using Losant library ver. 1.3.0 and JSON ver. 6.12.0

**Comment by InconceivableDuck** [comment]
Looks like the ArduinoJson library made some big changes to their API with v6. I'm working to update this library to support the changes.

**Comment by mwwojcik2017** [comment]
Thank you very much. Is there any progress on this one? I would like to re-compile my device...

**Comment by spacetc62** [comment]
the latest version (v2.0.0) now uses ArduinoJson v6 - see https://github.com/Losant/losant-mqtt-arduino/pull/15, so this should work now
