### ISSUE TITLE
handleCommand is not getting called

### ISSUE THREAD

**Issue by siddhpuraamitr** [Losant/losant-mqtt-arduino#8]
Hello, I have copied your example but I am getting problem

 My device id is 
const char* LOSANT_DEVICE_ID = "5aacb7f1f26c000007d1876a";

from "A" device, I am sending command to "B" device but in "B" device's handleCommand metod is not getting called

My workflow of "A" device is below, I have put virtual button for test that "B" is getting command or not 

<img width="665" alt="screen shot 2018-03-18 at 9 47 39 am" src="https://user-images.githubusercontent.com/1912476/37562550-8c3ce538-2a91-11e8-853c-6f55592970e0.png">

**Comment by cephirothdy2j** [comment]
This issue tracker is meant for any bugs related to our Arduino client. In the future, you should submit requests such as these within our [forums](https://forums.losant.com/).

That said, it appears you entered a device ID in for a [payload path](https://docs.losant.com/workflows/accessing-payload-data/#payload-paths). You should instead select the radio button above it to [choose a specific device](https://docs.losant.com/workflows/outputs/device-command/#configuration) and then send the command to the device matching that ID.

If you have any followup questions, please ask them in our forums.
